// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// De
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnIkw_g56R78xkduBPO1xWaK7IaQhaT84',
    appId: '1:129601420183:web:5f1f6f96f8441effa2a2d2',
    messagingSenderId: '129601420183',
    projectId: 'my-flutter-app-f4e1c',
    authDomain: 'my-flutter-app-f4e1c.firebaseapp.com',
    storageBucket: 'my-flutter-app-f4e1c.firebasestorage.app',
    measurementId: 'G-M87Z9WJX8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW-AZB4poO0HKHSQvuFYi0LIvlystMc98',
    appId: '1:129601420183:android:b1d837f2a4143e28a2a2d2',
    messagingSenderId: '129601420183',
    projectId: 'my-flutter-app-f4e1c',
    storageBucket: 'my-flutter-app-f4e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJlCIJK99oz7BNpXba5Pxwee53OCcZ6uY',
    appId: '1:129601420183:ios:d383dd0d05b25824a2a2d2',
    messagingSenderId: '129601420183',
    projectId: 'my-flutter-app-f4e1c',
    storageBucket: 'my-flutter-app-f4e1c.firebasestorage.app',
    iosClientId: '129601420183-1823gi6ds5pl0s98l7hfkeb734rn7tju.apps.googleusercontent.com',
    iosBundleId: 'com.example.my_flutter_application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJlCIJK99oz7BNpXba5Pxwee53OCcZ6uY',
    appId: '1:129601420183:ios:d383dd0d05b25824a2a2d2',
    messagingSenderId: '129601420183',
    projectId: 'my-flutter-app-f4e1c',
    storageBucket: 'my-flutter-app-f4e1c.firebasestorage.app',
    iosClientId: '129601420183-1823gi6ds5pl0s98l7hfkeb734rn7tju.apps.googleusercontent.com',
    iosBundleId: 'com.example.my_flutter_application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnIkw_g56R78xkduBPO1xWaK7IaQhaT84',
    appId: '1:129601420183:web:51fb5cba5ec9b076a2a2d2',
    messagingSenderId: '129601420183',
    projectId: 'my-flutter-app-f4e1c',
    authDomain: 'my-flutter-app-f4e1c.firebaseapp.com',
    storageBucket: 'my-flutter-app-f4e1c.firebasestorage.app',
    measurementId: 'G-J1T7W2045X',
  );

}