// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// De
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBbAwuu-ZbNffUKVtk3L-oB5n0ddgGXI',
    appId: '1:359857010342:web:2d8dae10b7eb4958f96667',
    messagingSenderId: '359857010342',
    projectId: 'my-flutter-app-e0c99',
    authDomain: 'my-flutter-app-e0c99.firebaseapp.com',
    storageBucket: 'my-flutter-app-e0c99.firebasestorage.app',
    measurementId: 'G-RDDLQY26VZ',
    databaseURL: 'https://my-flutter-app-e0c99-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyiud91K3Pz2UflJRidbGVmw0wc7QZVaY',
    appId: '1:359857010342:android:4956b803eb03aa58f96667',
    messagingSenderId: '359857010342',
    projectId: 'my-flutter-app-e0c99',
    storageBucket: 'my-flutter-app-e0c99.firebasestorage.app',
    databaseURL: 'https://my-flutter-app-e0c99-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_X-WiZAw8tSUZHODe_sWx3oMvJXISgHM',
    appId: '1:359857010342:ios:f85e3808e5755e67f96667',
    messagingSenderId: '359857010342',
    projectId: 'my-flutter-app-e0c99',
    storageBucket: 'my-flutter-app-e0c99.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApplication',
    databaseURL: 'https://my-flutter-app-e0c99-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_X-WiZAw8tSUZHODe_sWx3oMvJXISgHM',
    appId: '1:359857010342:ios:f85e3808e5755e67f96667',
    messagingSenderId: '359857010342',
    projectId: 'my-flutter-app-e0c99',
    storageBucket: 'my-flutter-app-e0c99.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApplication',
    databaseURL: 'https://my-flutter-app-e0c99-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBbAwuu-ZbNffUKVtk3L-oB5n0ddgGXI',
    appId: '1:359857010342:web:69f99ee109e9df64f96667',
    messagingSenderId: '359857010342',
    projectId: 'my-flutter-app-e0c99',
    authDomain: 'my-flutter-app-e0c99.firebaseapp.com',
    storageBucket: 'my-flutter-app-e0c99.firebasestorage.app',
    measurementId: 'G-4C30FLEW45',
    databaseURL: 'https://my-flutter-app-e0c99-default-rtdb.asia-southeast1.firebasedatabase.app',
    
  );
}
